# Generated by Django 5.1.7 on 2025-03-24 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('knowledge_type', models.CharField(choices=[('COURSE', 'Course Knowledge'), ('IDEOLOGY', 'Ideological Element')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('RELATED', 'Related To'), ('PART_OF', 'Part Of'), ('INFLUENCE', 'Influences'), ('EXAMPLE', 'Example Of')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relationships', to='knowledge_app.knowledgenode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relationships', to='knowledge_app.knowledgenode')),
            ],
            options={
                'unique_together': {('source', 'target', 'relationship_type')},
            },
        ),
    ]
